[keyboard.interlockConf]
depth = 1.0
lockWidth = 1.0
sectionWidth = 3.0
offsetSize = 0.2
widthMultiplier = 0.6
height = 1.1

[keyboard.blockConf]
baseHeight = 1.0
shellHeight = 3.0
topThickness = 0.7
shellThickness = 0.6
lidElevation = 0.5

[keyboard.exportConf]
exportMode = "modular"

[keyboard.defaultConf]
keyWidth = 1.8
keyHeight = 0.8
keyLength = 1.8
keySpacing = 0.5
rowSpacing = 0.25
keyInnerLength = 1.4
keyInnerWidth = 1.4
firstKeySpacing = 0.0

[[block]]
# Size of the left and right angle in the block
angles = { left = 90, right = 90 }
# Offset hull in the left and right from the convex hull
offsets = { left = 0.2, right = 0.2 }

[block.positioning]
id = 0
relativeTo = 1
pos = "rpLeft"
offset = 0.25

[block.dimensions]
width = 8.0 # Width of the keyboard block
lowerLen = 12.0 # Length of the lower side of the block.

[[block.row]]
# Define key using only button codes
keys = ["q", "w", "e", "9", "1"]

[[block.row]]
# Specify only number of keys in the row
keys = 5

[[block.row]]
# Specify only number of keys in the row
keys = 5
