== Requirements

* Raspberry pi zero
* 8+GB micro sd card
* Couple of usb wires

== Keyboard setup

=== Setup raspberry pi

Setup raspberry pi, connect to your wifi in headless mode
and ssh into it.

==== Install raspbian

* Download the latest image of Raspbian from  https://www.raspberrypi.org/downloads/raspbian/[here]
* Burn image to the sd card. I used https://www.balena.io/etcher/[etcher]
* Cd to sd card
  ** Create mount point `sudo mkdir /mnt/sdcard`
  ** Mount sd card to previously created folder `sudo mount /dev/sdX /mnt/sdcard`
  ** `cd /mnt/sdcard`
* Create a file named `ssh` in the root of the boot volume using `touch ssh`
* To preconfigure the Pi to connect to a WiFi network, create a file called wpa_supplicant.conf
  in the root of the boot volume with the following contents.

[source, bash]
----
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=<TWO_LETTER_ISO_COUNTRY_CODE>

network={
    ssid="<WIFI_NETWORK_NAME>"
    psk="<WIFI_PASSWORD>"
    key_mgmt=WPA-PSK
}
----
* Unmount sd card using `sudo umount /mnt/sdcard`, eject it and insert it into the
  Raspberry PI. When unmounting make sure that you are not in the same folder
  because this might cause `*umount: /mnt/sdcard: target is busy*` error.
  If you want to force unmount sd card you might use `-l` option.

==== Install required packages

Before proceding with packages that are mandatory for installation I recommend
you to spent ~10 minutes of your time by installing `fish` and `neovim`. Of course
you can choose any other text editor and shell. To use vim under sudo and still
have all your settings use `sudo -E nvim`

Installation as follows:
[source, bash]
----
sudo apt-get install neovim zsh
# Last one is optional: download and isntall my vim config: very minimalistic (only 18 lines).
# You can replace it any other config you want
mkdir -p ~/.config/nvim/
curl https://gitlab.com/snippets/1770471/raw >> ~/.config/nvim/init.vim
----


===== Install rust

[source, bash]
----
sudo apt-get install rustc
----

== Devnotes

=== USB Hid


Input reports are those sent from the keyboard to the computer.

* 1 byte: modifier keys (Control, Shift, Alt, etc.), where each bit corresponds to a key
* 1 byte: unused/reserved for OEM
* 6 bytes: pressed key codes

In order to press a regular key (e.g. A or B), its code has to be included
inside the 6 byte segment. Remember that this segment represents the pressed
keys, so until a key stops appearing there the host will keep pressing that key
constantly.

The modifier keys, however, are 1 bit each. The modifier byte has the following
structure (bit 0 is on the rightmost part):

1. Right Meta
2. Right Alt
3. Right Shift
4. Right Control
5. Left Meta
6. Left Alt
7. Left Shift
8. Left Control

If a given bit is set to 1, then the modifier key in
question is pressed.

=== General algorithm


==== In short

Scan all keyboard, if any changes in pressed keys form new usb report
and send it to PC.

==== More detailed

Main algorithm is divided into several stages.
. Scan all keypads to determine which keys has been changed.
. If no keys changed between scans do nothing
. For each changed key
  ** If this key has controlled some of the modifiers determine
      whether or not this modifier is still activated by some other key.
      If this is not the case toggle modifier off.
  ** After determining which modifers are activated on this keypad
      add modifiers from other keypads.
  ** For each pressed key determine key code that will be sent to the
      PC.
. After previous stage we have
  1. List of currently pressed modifier keys
  2. List of key codes that should be sent to the PC

  Create report that will be sent to the pc

  [ditaa, report_structire, png]
  ....
  /--------------------------\
  | 8-bit modifier key codes |
  +--------------------------+
  | OEM reserved             |
  +--------------------------+
  | Key code                 |
  +--------------------------+
  | Key code                 |
  +--------------------------+
  | Key code                 |
  +--------------------------+
  | Key code                 |
  +--------------------------+
  | Key code                 |
  +--------------------------+
  | Key code                 |
  \--------------------------/
  ....

== Links

Links to articles and forum discussions that I found to be really useful
when making this keyboard

* https://www.rmedgar.com/blog/using-rpi-zero-as-keyboard-send-reports[RPI as keyboard send reports]
* https://medium.com/@maheshsenni/setting-up-a-raspberry-pi-without-keyboard-and-mouse-headless-9359e0926807[Setting up a Raspberry Pi without keyboard and mouse (headless)]
