
run_vllm_script infile outfile:
  uv run --no-project local/vllm_run.py \
    --input {{infile}} \
    --output {{outfile}} \
    --vllm-url "$RUNPOD_VLLM_URL" \
    --ssh-host "$RUNPOD_SSH_HOST" \
    --ssh-port "$RUNPOD_SSH_PORT" \
    --ssh-user "$RUNPOD_SSH_USER" \
    --ssh-key "$RUNPOD_SSH_KEY"

run_llama infile outfile llama_url *ARGS:
  uv run --no-project local/llama_run_docling.py \
    --input {{infile}} \
    --output {{outfile}} \
    --llama-server-url {{llama_url}} \
    {{ARGS}}
