#!/usr/bin/env sh
# -*- mode: GNUMakefile; -*-

tmp=$(mktemp "/tmp/XXXXXXXXXX.make")
sed '0,/^# --- start ---$/ s/.*/ /' "$0" > $tmp
echo $tmp
exec make --directory=$(pwd) --makefile=$tmp

# --- start ---

printer := $(shell																						\
	if [[ res=$(which colecho 2> /dev/null) && ! -z "$res" ]];	\
	then																												\
		echo "colecho";																						\
		else																											\
		echo "echo -- ";																					\
	fi																													\
)

log := $(printer)
wrn := $(printer) -w
err := $(printer) -e
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))

.ONESHELL:
default: \
	show-message-printers \
	start-automatic-rebuild \
	format-code \
	help


.oneshell:
show-message-printers:
	@echo $(printer)
	$(log) hello
	$(wrn) test
	$(err) asdfasdf

.oneshell:
help:
	@true
	## Show documentation for all build targets
	$(log) $(mkfile_path)

.oneshell:
build:
	@$(log) Starting build

.oneshell:
format-code:
	@$(log) Format code for the project
	fd -e cpp -e hpp | while read -r file; do
		$(log) -I:3 Formatting "$$file"
		clang-format -i "$$file"
	done

.oneshell:
start-automatic-rebuild:
	@$(wrn) Starting automatic rebuild.
	$(log) To exit press 'q'
