conan: 
    conan install . --output-folder=.conan_install -pr:h=conanprofile.txt --build=missing -s build_type=RelWithDebInfo

configure: conan
    cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="$PWD/.conan_install/build/RelWithDebInfo/generators/conan_toolchain.cmake"

build: configure
    cmake --build build --config RelWithDebInfo 

run: build 
    ./build/trace_event_cli \
        --input-dir ~/defaultdirs/workspace/haxorg/build/haxorg_debug_instrumented \
        --output-db /tmp/haxorg-db.duckdb \
        --max-trace-file 5

test: build
    ./build/trace_event_test        

bench: build
    ./build/trace_event_bench

debug_test: build
    lldb ./build/trace_event_test        
