rowPins = [1 ]
colPins = [3, 4, 5]
modifiers = ["math"]

# [[row]]
# keys = ["alt-", "ctrl-", "meta-"]

[[row]]
keys = [
  [ "shift-" ],
  [ "," ],
  [ [ "math", "ctrl-c ctrl-c" ],
    [ "default", "ctrl-c ctrl-v"] ]
]

# [[row]]
# keys = ["H", "E", "N"]
