target=`cat target.txt`
run:
	make $(target)
	./$(target)

class_defintions: class_defintions.cpp
	clang++ class_definitions.cpp

variant_object: variant-object.cpp
	clang++ variant-object.cpp -o variant_object
