version: 3

tasks:
  nim_ast_diff:
    desc: "Build ad execute nim AST diff port"
    vars:
      NAME: nim_ast_diff_port
    cmds:
      - nim r {{.NAME}}.nim

  clang_ast_diff:
    desc: "Build and execute clang AST diff port"
    vars:
      NAME: clang_ast_diff_port
    cmds:
      - >
        clang++
        -std=c++2a
        -g
        -ferror-limit=2
        -o
        {{.NAME}}.bin
        {{.NAME}}.cpp

      - ./{{.NAME}}.bin

  gcc_instrumentation:
    desc: "Create GCC instrumentation log for a file"
    cmds:
      - >
        clang++
        -g
        -ldl
        -Wl,--export-dynamic
        -finstrument-functions
        {{.NAME}}.cpp
        -o {{.NAME}}.bin

      - clang++ {{.NAME}}_analyze.cpp -std=c++20 -o {{.NAME}}_analyze.bin
      - ./{{.NAME}}.bin cyg_profile_trace1.log no_special_sym || true
      - ./{{.NAME}}.bin cyg_profile_trace2.log inputqqq || true
      - ./{{.NAME}}_analyze.bin cyg_profile_trace1.log cyg_profile_trace2.log {{.PWD}}/{{.NAME}}.bin

    vars:
      NAME: cyg_profile_trace
