run_ocr input_path db_path *ARGS:
  rm {{db_path}}
  uv run \
    --no-project python -m ocr_db.collect.ocr_driver \
    {{input_path}} \
    {{db_path}} \
    {{ARGS}}

run_gui input_path:
  PYTHONPATH=src uv run \
    --no-project python -m ocr_db.gui.main_window \
    {{input_path}}

install_requirements: 
  uv pip install -r requirements.txt
