gen_dir := "gen"

gen haxorg_project_root:
    mkdir -p {{gen_dir}}
    uv run python -m grpc_tools.protoc \
        -I {{haxorg_project_root}} \
        --plugin=protoc-gen-python_betterproto={{justfile_directory()}}/.venv/bin/protoc-gen-python_betterproto2 \
        --python_betterproto_out={{gen_dir}} \
        --python_betterproto_opt=GOOGLE_PROTOBUF_SPECIAL_PACKAGE \
        {{haxorg_project_root}}/src/haxorg/serde/SemOrgProto.proto \
        {{haxorg_project_root}}/src/hstd/ext/graph/base/graph_base.proto \
        {{haxorg_project_root}}/src/haxorg/imm/ImmOrgGraph.proto

run *ARGS:
    uv run python main.py {{ARGS}} | fjson --max-width 400 --max-inline-complexity 6 --max-table-complexity 6 

run_gui cli input *ARGS:
    uv run python tree_view_gui.py {{cli}} {{input}} {{ARGS}}

run_flat_gui cli input *ARGS:
    uv run python flat_view_gui.py {{cli}} {{input}} {{ARGS}}

run_igraph_from_proto input *ARGS:
    uv run python import_graph.py {{input}} {{ARGS}}
