version: 3
tasks:
  generate_grammar:
    cmds:
      - antlr4 -Dlanguage=Cpp -visitor -o {{.grammar_name}}_build {{.grammar_name}}.g4


  compile_grammar:
    cmds:
      - >
        clang++
        -std=c++20
        -g
        -l antlr4-runtime
        -I/usr/include/antlr4-runtime/
        -ferror-limit=1
        -o {{.grammar_name}}_build.bin
        {{.grammar_name}}_build/*.cpp
        {{.grammar_name}}_user.cpp

  generate_and_compile:
    cmds:
      - task: generate_grammar
        vars:
          grammar_name: "{{.grammar_name}}"

      - task: compile_grammar
        vars:
          grammar_name: "{{.grammar_name}}"

  run_debug:
    cmds:
      - "{{.EXPR}} || rr record {{.EXPR}}"

  full_cycle:
    desc: "Run test grammar execution"
    cmds:
      - task: generate_and_compile
        vars:
          grammar_name: "test_grammar"

      - task: run_debug
        vars:
          EXPR: "./{{.grammar_name}}_build.bin {{.grammar_name}}_input.txt"

  test_grammar:
    desc: "Run test grammar execution"
    cmds:
      - task: full_cycle
        vars:
          grammar_name: "test_grammar"

  custom_lexer:
    desc: "Run test grammar execution"
    cmds:
      - task: full_cycle
        vars:
          grammar_name: "custom_lexer"
