[project]
name = "archivebox-rebuild"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "archivebox==0.7.2",
    "beartype>=0.22.9",
    "loguru>=0.7.3",
    "lxml>=6.1.1",
    "readability-lxml>=0.8.4.1",
    "setuptools>=84.0.0",
    "trafilatura>=2.2.0",
]
