[meta]
language = "c++"

[pckgconfig]
name = "testpackage"
version = "0.1"
user = "demo"
channel = "testing"
package_type = "library"

[buildconfig]
conan_build_folder = "build"
conan_reqs_folder = "conan"
build_system = "qmake"
copy_to_build = [ "*.hpp", "*.cpp", "*.pro" ]
libtype = "static"

[exportconfig]
library_globs = [ "*.a" ]
header_folder = "include/libname"
header_globs = [ "*.hpp" ]
