[project]
name = "graphviz-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "haxscramper", email = "haxscramper@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.22.9",
    "plumbum>=2.0.2",
    "pydot>=4.0.1",
    "pyqt6>=6.11.0",
]

[project.scripts]
graphviz-viewer = "graphviz_viewer:main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"
